export default {
  REQUEST_LOGIN: "REQUEST_LOGIN",
  LOGIN_REQUEST_SUCCESS: "LOGIN_REQUEST_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",
  RESET_SIGNIN_STATE: "RESET_SIGNIN_STATE",
  STORE_USER: "STORE_USER",
};
