export const actionTypes = {
	GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
	RECEIVE_PRODUCTS: "RECEIVE_PRODUCTS",
	GET_ALL_ORDERS: "GET_ALL_ORDERS",
	LOAD_PRODUCTS: "LOAD_PRODUCTS",
	GET_ERRORS: "GET_ERRORS",
};
